# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:20
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0020_auto_20171211_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=64, populate_from='text', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='forum_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('activity', 'Activity')], default='discussion', max_length=64, verbose_name='Forum Type'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=64, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topicnotification',
            name='action',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('mention', 'Mention'), ('comment', 'Comment'), ('new_topic', 'New Topic'), ('new_comment', 'New Comment'), ('new_reaction', 'New Reaction'), ('new_reaction_comment', 'New Reaction to a Comment'), ('new_activity', 'New activity')], default='undefined', max_length=64),
        ),
    ]
