# Generated by Django 2.2.5 on 2019-09-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0021_auto_20180628_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnreadNotification',
        ),
    ]
