# Generated by Django 2.2.13 on 2020-06-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0021_forumfile'),
        ('discussion', '0022_delete_unreadnotification'),
    ]

    operations = [
    ]
