# Generated by Django 2.2.17 on 2021-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0025_topic_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forum_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('activity', 'Activity'), ('course', 'Course')], default='discussion', max_length=64, verbose_name='Forum Type'),
        ),
    ]
