# Generated by Django 2.2.16 on 2020-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0025_topic_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='forum',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='pinned'),
        ),
    ]
