# Generated by Django 2.2.24 on 2021-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0026_auto_20210319_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
