# Generated by Django 2.2.24 on 2021-07-17 15:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0026_auto_20210319_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='forum',
            name='slug_es',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='forum',
            name='slug_pt_br',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='forum',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='forum',
            name='text_es',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='forum',
            name='text_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_es',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=64, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_es',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=64, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_pt_br',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=64, null=True, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
