# Generated by Django 2.2.24 on 2021-07-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0027_auto_20210719_1111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topiclike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topicnotification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topicread',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topicuse',
            unique_together=set(),
        ),
    ]
