# Generated by Django 2.2.27 on 2022-02-12 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0029_auto_20210812_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicread',
            unique_together={('user', 'topic')},
        ),
    ]
